name = "pong-lobby"
main = "src/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "PONG_LOBBY", class_name = "PongLobby" },
  { name = "PONG_MATCH", class_name = "PongMatch" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PongLobby", "PongMatch"]
